// Lista curada das principais cidades brasileiras agrupadas por estado.
// Usada no hub /cidades para SEO e distribuição de autoridade interna.
export const CIDADES_BR: Record<string, { cidade: string; label: string }[]> = {
  AC: [{ cidade: "Rio-Branco", label: "Rio Branco" }],
  AL: [{ cidade: "Maceio", label: "Maceió" }, { cidade: "Arapiraca", label: "Arapiraca" }],
  AP: [{ cidade: "Macapa", label: "Macapá" }],
  AM: [{ cidade: "Manaus", label: "Manaus" }],
  BA: [
    { cidade: "Salvador", label: "Salvador" },
    { cidade: "Feira-de-Santana", label: "Feira de Santana" },
    { cidade: "Vitoria-da-Conquista", label: "Vitória da Conquista" },
    { cidade: "Ilheus", label: "Ilhéus" },
  ],
  CE: [
    { cidade: "Fortaleza", label: "Fortaleza" },
    { cidade: "Caucaia", label: "Caucaia" },
    { cidade: "Juazeiro-do-Norte", label: "Juazeiro do Norte" },
  ],
  DF: [{ cidade: "Brasilia", label: "Brasília" }],
  ES: [
    { cidade: "Vitoria", label: "Vitória" },
    { cidade: "Vila-Velha", label: "Vila Velha" },
    { cidade: "Serra", label: "Serra" },
  ],
  GO: [
    { cidade: "Goiania", label: "Goiânia" },
    { cidade: "Aparecida-de-Goiania", label: "Aparecida de Goiânia" },
    { cidade: "Anapolis", label: "Anápolis" },
  ],
  MA: [{ cidade: "Sao-Luis", label: "São Luís" }],
  MT: [{ cidade: "Cuiaba", label: "Cuiabá" }, { cidade: "Varzea-Grande", label: "Várzea Grande" }],
  MS: [{ cidade: "Campo-Grande", label: "Campo Grande" }, { cidade: "Dourados", label: "Dourados" }],
  MG: [
    { cidade: "Belo-Horizonte", label: "Belo Horizonte" },
    { cidade: "Uberlandia", label: "Uberlândia" },
    { cidade: "Contagem", label: "Contagem" },
    { cidade: "Juiz-de-Fora", label: "Juiz de Fora" },
    { cidade: "Betim", label: "Betim" },
    { cidade: "Montes-Claros", label: "Montes Claros" },
  ],
  PA: [{ cidade: "Belem", label: "Belém" }, { cidade: "Ananindeua", label: "Ananindeua" }],
  PB: [{ cidade: "Joao-Pessoa", label: "João Pessoa" }, { cidade: "Campina-Grande", label: "Campina Grande" }],
  PR: [
    { cidade: "Curitiba", label: "Curitiba" },
    { cidade: "Londrina", label: "Londrina" },
    { cidade: "Maringa", label: "Maringá" },
    { cidade: "Ponta-Grossa", label: "Ponta Grossa" },
    { cidade: "Cascavel", label: "Cascavel" },
    { cidade: "Foz-do-Iguacu", label: "Foz do Iguaçu" },
  ],
  PE: [
    { cidade: "Recife", label: "Recife" },
    { cidade: "Jaboatao-dos-Guararapes", label: "Jaboatão dos Guararapes" },
    { cidade: "Olinda", label: "Olinda" },
    { cidade: "Caruaru", label: "Caruaru" },
  ],
  PI: [{ cidade: "Teresina", label: "Teresina" }],
  RJ: [
    { cidade: "Rio-de-Janeiro", label: "Rio de Janeiro" },
    { cidade: "Sao-Goncalo", label: "São Gonçalo" },
    { cidade: "Duque-de-Caxias", label: "Duque de Caxias" },
    { cidade: "Nova-Iguacu", label: "Nova Iguaçu" },
    { cidade: "Niteroi", label: "Niterói" },
    { cidade: "Campos-dos-Goytacazes", label: "Campos dos Goytacazes" },
  ],
  RN: [{ cidade: "Natal", label: "Natal" }, { cidade: "Mossoro", label: "Mossoró" }],
  RS: [
    { cidade: "Porto-Alegre", label: "Porto Alegre" },
    { cidade: "Caxias-do-Sul", label: "Caxias do Sul" },
    { cidade: "Pelotas", label: "Pelotas" },
    { cidade: "Canoas", label: "Canoas" },
    { cidade: "Santa-Maria", label: "Santa Maria" },
  ],
  RO: [{ cidade: "Porto-Velho", label: "Porto Velho" }, { cidade: "Ji-Parana", label: "Ji-Paraná" }],
  RR: [{ cidade: "Boa-Vista", label: "Boa Vista" }],
  SC: [
    { cidade: "Florianopolis", label: "Florianópolis" },
    { cidade: "Joinville", label: "Joinville" },
    { cidade: "Blumenau", label: "Blumenau" },
    { cidade: "Chapeco", label: "Chapecó" },
    { cidade: "Criciuma", label: "Criciúma" },
  ],
  SP: [
    { cidade: "Sao-Paulo", label: "São Paulo" },
    { cidade: "Guarulhos", label: "Guarulhos" },
    { cidade: "Campinas", label: "Campinas" },
    { cidade: "Sao-Bernardo-do-Campo", label: "São Bernardo do Campo" },
    { cidade: "Santo-Andre", label: "Santo André" },
    { cidade: "Osasco", label: "Osasco" },
    { cidade: "Ribeirao-Preto", label: "Ribeirão Preto" },
    { cidade: "Sorocaba", label: "Sorocaba" },
    { cidade: "Santos", label: "Santos" },
    { cidade: "Sao-Jose-dos-Campos", label: "São José dos Campos" },
    { cidade: "Bauru", label: "Bauru" },
    { cidade: "Piracicaba", label: "Piracicaba" },
  ],
  SE: [{ cidade: "Aracaju", label: "Aracaju" }],
  TO: [{ cidade: "Palmas", label: "Palmas" }],
};

export const ESTADOS_BR_NOMES: Record<string, string> = {
  AC: "Acre", AL: "Alagoas", AP: "Amapá", AM: "Amazonas", BA: "Bahia",
  CE: "Ceará", DF: "Distrito Federal", ES: "Espírito Santo", GO: "Goiás",
  MA: "Maranhão", MT: "Mato Grosso", MS: "Mato Grosso do Sul", MG: "Minas Gerais",
  PA: "Pará", PB: "Paraíba", PR: "Paraná", PE: "Pernambuco", PI: "Piauí",
  RJ: "Rio de Janeiro", RN: "Rio Grande do Norte", RS: "Rio Grande do Sul",
  RO: "Rondônia", RR: "Roraima", SC: "Santa Catarina", SP: "São Paulo",
  SE: "Sergipe", TO: "Tocantins",
};
