// Constantes do Guia Local BR

export const SITE_NAME = "Guia Local BR";
export const SITE_DESCRIPTION = "Conecte-se aos melhores negócios locais e impulsione sua visibilidade!";
export const SITE_URL = "https://guialocalbr.com.br";

// Admin
export const ADMIN_EMAIL = "gestorederoliveira@gmail.com";

// WhatsApp
export const WHATSAPP_NUMBER = "5535999483143";
export const WHATSAPP_SUPPORT_LINK = `https://wa.me/${WHATSAPP_NUMBER}?text=Olá, tenho dúvida no Guia Local BR!`;
export const WHATSAPP_PREMIUM_LINK = `https://wa.me/${WHATSAPP_NUMBER}?text=Olá, quero conhecer o plano Premium vitalício do Guia Local BR.`;

// Pagamento — Plano Premium vitalício. Ativação manual via WhatsApp (sem valores expostos no site).
export const PAYMENT_LINK = WHATSAPP_PREMIUM_LINK;
export const INFINITEPAY_HANDLE = "ederoliveiradigital";

// Estados brasileiros
export const ESTADOS_BR = [
  { sigla: "AC", nome: "Acre" },
  { sigla: "AL", nome: "Alagoas" },
  { sigla: "AP", nome: "Amapá" },
  { sigla: "AM", nome: "Amazonas" },
  { sigla: "BA", nome: "Bahia" },
  { sigla: "CE", nome: "Ceará" },
  { sigla: "DF", nome: "Distrito Federal" },
  { sigla: "ES", nome: "Espírito Santo" },
  { sigla: "GO", nome: "Goiás" },
  { sigla: "MA", nome: "Maranhão" },
  { sigla: "MT", nome: "Mato Grosso" },
  { sigla: "MS", nome: "Mato Grosso do Sul" },
  { sigla: "MG", nome: "Minas Gerais" },
  { sigla: "PA", nome: "Pará" },
  { sigla: "PB", nome: "Paraíba" },
  { sigla: "PR", nome: "Paraná" },
  { sigla: "PE", nome: "Pernambuco" },
  { sigla: "PI", nome: "Piauí" },
  { sigla: "RJ", nome: "Rio de Janeiro" },
  { sigla: "RN", nome: "Rio Grande do Norte" },
  { sigla: "RS", nome: "Rio Grande do Sul" },
  { sigla: "RO", nome: "Rondônia" },
  { sigla: "RR", nome: "Roraima" },
  { sigla: "SC", nome: "Santa Catarina" },
  { sigla: "SP", nome: "São Paulo" },
  { sigla: "SE", nome: "Sergipe" },
  { sigla: "TO", nome: "Tocantins" },
];

// Nichos de negócios (ordenados alfabeticamente)
export const NICHOS = [
  "Academia",
  "Acessórios",
  "Açaí e Sorveteria",
  "Advocacia",
  "Agência de Viagens",
  "Agropecuária",
  "Alimentação",
  "Aluguel de Carros",
  "Aluguel de Equipamentos",
  "Ar Condicionado",
  "Arquitetura",
  "Artesanato",
  "Assistência Técnica",
  "Ateliê",
  "Auto Elétrica",
  "Auto Peças",
  "Automotivo",
  "Bar e Petiscaria",
  "Barbearia",
  "Beleza e Estética",
  "Bicicletaria",
  "Borracharia",
  "Buffet e Catering",
  "Cabeleireiro",
  "Cafeteria",
  "Câmeras e Monitoramento",
  "Carrinho Gourmet",
  "Casa e Decoração",
  "Chaveiro",
  "Churrascaria",
  "Cigarro Eletrônico / Tabacaria",
  "Clínica de Estética",
  "Clínica Médica",
  "Clínica Odontológica",
  "Comida Caseira / Marmitas",
  "Confeitaria",
  "Consultoria",
  "Construção",
  "Contabilidade",
  "Conveniência",
  "Costureira",
  "Coworking",
  "Creche e Berçário",
  "Day Use / SPA",
  "Dedetização",
  "Depilação",
  "Depósito de Bebidas",
  "Depósito de Gás",
  "Design",
  "Despachante",
  "Doceria",
  "Educação",
  "Eletricista",
  "Eletrodomésticos",
  "Eletrônicos",
  "Encanador",
  "Energia Solar",
  "Engenharia",
  "Entretenimento",
  "Escola de Idiomas",
  "Escritório Virtual",
  "Esportes",
  "Estacionamento",
  "Estética Automotiva",
  "Eventos e Festas",
  "Farmácia",
  "Ferragens",
  "Festas Infantis",
  "Financeira / Crédito",
  "Fisioterapia",
  "Floricultura",
  "Fotografia",
  "Funilaria e Pintura",
  "Geek e Colecionáveis",
  "Gesseiro",
  "Gráfica",
  "Guincho",
  "Hamburgueria",
  "Hortifruti",
  "Hotel e Pousada",
  "Igreja / Templo",
  "Imobiliário",
  "Importados",
  "Informática",
  "Instalação de Som Automotivo",
  "Jardinagem",
  "Joalheria",
  "Lava-Jato",
  "Lavanderia",
  "Limpeza",
  "Livraria",
  "Locação de Imóveis",
  "Loja de Bebidas",
  "Loja de Calçados",
  "Loja de Departamento",
  "Loja de Festa",
  "Loja de Presentes",
  "Loja de Roupas",
  "Loteamento",
  "Lotérica",
  "Manicure e Pedicure",
  "Manutenção",
  "Marcenaria",
  "Marketing",
  "Marketing Digital",
  "Marmoraria",
  "Massoterapia",
  "Materiais de Construção",
  "Mecânica Industrial",
  "Mecânica de Motos",
  "Mercadinho",
  "Moda",
  "Móveis Planejados",
  "Moto Peças",
  "Motoboy / Entregas",
  "Mudanças e Fretes",
  "Música",
  "Nail Designer",
  "Nutrição",
  "Oficina Mecânica",
  "Ótica",
  "Ourivesaria",
  "Padaria",
  "Papelaria",
  "Pastelaria",
  "Perfumaria",
  "Personal Trainer",
  "Pet Shop",
  "Piscinas",
  "Pintura",
  "Pizzaria",
  "Portões Automáticos",
  "Posto de Combustível",
  "Pré-Escola / Educação Infantil",
  "Produtos Naturais",
  "Psicologia",
  "Reciclagem / Ferro Velho",
  "Reformas",
  "Refrigeração",
  "Relojoaria",
  "Restaurante",
  "Salão de Beleza",
  "Salão de Festas",
  "Sapataria",
  "Saúde",
  "Segurança",
  "Seguros",
  "Serralheria",
  "Serviços Gerais",
  "Sex Shop",
  "Sorveteria",
  "Supermercado",
  "Suplementos",
  "Sushi e Comida Japonesa",
  "Tapeçaria",
  "Tattoo e Piercing",
  "Táxi e Transporte de Passageiros",
  "Tecnologia",
  "Telecomunicações",
  "Terapias Holísticas",
  "Tornearia",
  "Transporte",
  "Transporte Escolar",
  "Turismo",
  "Varejo",
  "Vending Machine",
  "Veterinária",
  "Vidraçaria",
  "Vistoria Veicular",
  "Web Design",
  "Outros",
];


// Links sociais Eder Oliveira
export const SOCIAL_LINKS = {
  youtube: "https://www.youtube.com/@ederoliveiradigital",
  pinterest: "https://www.pinterest.com/ederoliveiradigital/",
  linkedin: "https://www.linkedin.com/in/ederoliveiradigital/",
  instagram: "https://www.instagram.com/ederoliveiradigital/",
  tiktok: "https://www.tiktok.com/@ederoliveiradigital",
  facebook: "https://www.facebook.com/agenciaeckmidias",
  gmn: "https://share.google/6L8U3USO3beUj2OLA",
  threads: "https://www.threads.com/@ederoliveiradigital",
  whatsapp: `https://wa.me/${WHATSAPP_NUMBER}?text=Olá, vim pelo Guia Local BR!`,
  email: "ederoliveira@ederoliveiradigital.com.br",
  blog: "https://blog.ederoliveiradigital.com.br/",
  siteOficial: "https://ederoliveiradigital.com.br/",
  gmnTurbo: "https://gmnturbo.com.br/",
  prospectorTurbo: "https://prospectorturbo.com.br",
  agendaFlowPro: "https://agendaflowpro.online",
  qrCodeReview: "https://qrcodereview.online",
  zapZapPro: "https://zapzapflow.online",
  fluxoSocialPro: "http://fluxosocialpro.online",
  guiaLocalBr: "https://guialocalbr.com.br",
};

// Limites de upload
export const UPLOAD_LIMITS = {
  free: {
    fotos: 1,
    videos: 0,
  },
  premium: {
    fotos: 10,
    videos: 2,
  },
};

// Limites de parceiros (cota padrão — pode ser sobrescrita individualmente no admin)
export const PARCEIRO_LIMITS = {
  premiumEmpresas: 30,
};

// Níveis de parceiro com identidade visual
export type NivelParceiro = "bronze" | "prata" | "ouro" | "diamante";

export const NIVEIS_PARCEIRO: Record<
  NivelParceiro,
  { label: string; emoji: string; color: string; bg: string; border: string; gradient: string; cotaPremium: number }
> = {
  bronze: {
    label: "Bronze",
    emoji: "🥉",
    color: "text-amber-700 dark:text-amber-500",
    bg: "bg-amber-100 dark:bg-amber-950/40",
    border: "border-amber-700/40",
    gradient: "from-amber-700 to-amber-500",
    cotaPremium: 10,
  },
  prata: {
    label: "Prata",
    emoji: "🥈",
    color: "text-slate-600 dark:text-slate-300",
    bg: "bg-slate-100 dark:bg-slate-800/60",
    border: "border-slate-400/40",
    gradient: "from-slate-500 to-slate-300",
    cotaPremium: 30,
  },
  ouro: {
    label: "Ouro",
    emoji: "🥇",
    color: "text-yellow-700 dark:text-yellow-400",
    bg: "bg-yellow-100 dark:bg-yellow-950/40",
    border: "border-yellow-500/40",
    gradient: "from-yellow-500 to-amber-400",
    cotaPremium: 60,
  },
  diamante: {
    label: "Diamante",
    emoji: "💎",
    color: "text-cyan-700 dark:text-cyan-300",
    bg: "bg-cyan-100 dark:bg-cyan-950/40",
    border: "border-cyan-400/40",
    gradient: "from-cyan-500 to-blue-500",
    cotaPremium: 150,
  },
};
